services:
  database:
    image: 'postgres:latest'
    env_file:
      - './.env'
    ports:
      - '$POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT'
    environment:
      - 'POSTGRES_USER=$POSTGRESDB_USER'
      - 'POSTGRES_DB=$POSTGRESDB_DB'
      - 'POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD'
