services:
  database:
    image: 'postgres:latest'
    env_file:
      - './.env'
    ports:
      - '$POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT'
    environment:
      - 'POSTGRES_USER=$POSTGRESDB_USER'
      - 'POSTGRES_DB=$POSTGRESDB_DB'
      - 'POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD'

#volumes:
#  postgres-data:
#
#services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - POSTGRES_USER=raivydas
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=chessappdb
##      - .env
#    ports:
#      - '5432:5432'
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
#
#  app:
#    build: .
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/chessappdb
#      SPRING_DATASOURCE_USERNAME: raivydas
#      SPRING_DATASOURCE_PASSWORD: 1234
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
