DROP TABLE IF EXISTS CHESS_GAME;
DROP TABLE IF EXISTS CHESS_FILE;

-- Create a table to store game files
CREATE TABLE IF NOT EXISTS CHESS_FILE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    file LONGBLOB NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL
  );

-- Create a table to store user information
CREATE TABLE IF NOT EXISTS CHESS_GAME (
    id INT AUTO_INCREMENT PRIMARY KEY,
    white_player VARCHAR(20) NOT NULL,
    black_player VARCHAR(20) NOT NULL,
    result VARCHAR(5) NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    game_file_id INT,
    FOREIGN KEY (game_file_id) REFERENCES CHESS_FILE(id)
);
